### ISSUE TITLE
No ssh package in 1.2.0

### ISSUE THREAD

**Issue by adamlc** [cedvan/docker-toran-proxy#27]
I've tried using 1.2.0 but unfortunately it looks like the SSH package isn't installed, which causes issues when cloning private repos. 

Installing SSH stopped that error (`apt-get install ssh`) but unfortunately I then got `Host key verification failed. fatal: Could not read from remote repository.` during the sync cron, despite my ssh keys being present. I downgraded and it seemed to work again.

**Comment by cedvan** [comment]
Hi,

Hum, `ssh` was present on old base image. I changed the base image to increase safety and lightness, but I have not thought about the package `ssh`, I'll add it.

Thank you for issue

**Comment by cedvan** [comment]
Hi,

I've fix release 1.2.0, can you pull again and try ?

Thank you

**Comment by cedvan** [comment]
Solved with https://github.com/cedvan/docker-toran-proxy/commit/acea9f9bbc1c374fb2e8f150105dcb5fa86ac497

**Comment by cedvan** [comment]
you confirm ?

**Comment by adamlc** [comment]
@cedvan unfortunately it still doesn't seem to work. Getting the following error during sync:

```
error: cannot run ssh: No such file or directory
fatal: unable to fork
error: Could not fetch origin
```

**Comment by cedvan** [comment]
Ok, I'll try to fix tonight :wink:

**Comment by cedvan** [comment]
Ok, I fixed version 1.2.0, you can try ?

**Comment by adamlc** [comment]
@cedvan that fixed it! Working perfectly now thanks :+1:

**Comment by cedvan** [comment]
Ok great ! I close :wink:

**Comment by jeremyzahner** [comment]
@cedvan @adamlc Its not working for me. As far as i can see the ssh-agent is not running. How did you set it up exactly @adamlc?

**Comment by adamlc** [comment]
@jeremyzahner I set us up as per the documentation. Are you sure your image is up to date?

**Comment by jeremyzahner** [comment]
@adamlc Yes. I set it up via docker-cloud tough. Strange thing is, that inside the container there seems to be no ssh-agent running.

**Comment by adamlc** [comment]
Some logs or something may help 👍
